1. ตรวจสอบว่ามี Library ของ Numpy ถูกติดตั้งก่อนหรือไม่

In [ ]:
!pip show numpy

2. ถ้ายังไม่ได้ติดัังให้ทำการติดตั้ง Library ของ numpy โดยใช้คำสั่ง

In [ ]:
!pip install numpy

3. การสร้าง array ใน Numpy สามารถทำได้โดยใช้คำสั่ง np.array()

In [ ]:
import numpy as np
# Array แบบ 1 and n dimension 
# Array แบบ Scalar
# Array แบบ Vector 
a = np.array(10)
print(a)

row = np.array([1,2,3]) # 1 row 3 columns
colum = np.array([[4],[5],[6]])

print(colum)
print(row)

# Array แบบ Matrix  2 rows ,3 columns
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)



4. การสร้างตัวเลขสุ่ม ใน Numpy สามารถใช้ func np.random

In [65]:
# ตัวอย่างการ Random เลขจำนวนเต็ม 0-9 ขนาด 5 ตัว 

ran1 = np.random.randint(0,10,5) # เราจะได้ Vector 1 row 5 columns
print(ran1)

ran2 = np.random.random(5)
print(ran2)


[4 4 2 7 7]
[0.67308801 0.70883032 0.72205876 0.15316203 0.18736029]


5. ในตัว numpy สามารถเข้าถึง สมาชิกใน array และสามารถเลือกสมาชิกใน array ด้วย numpy

In [ ]:
vrow = np.array([1,2,3,4,5,6,7,8,9,10]) # 1 row 10 columns

print(vrow) #แสดงค่าทั้งหมดของ Array 
print(vrow[3]) #แสดงค่าตำแหน่ง 3 ของ Array 

print(vrow[2:6])  # แสดงค่าตำแหน่งที่ 2-6 มันจะไม่เอา ตำแหน่งที่ 6 
print(vrow[:5]) # แสดงค่าตำแหน่ง 0-5
print(vrow[6:]) # แสดงค่าตำแหน่ง ที่ 6 จนถึงสุดท้าย 
print(vrow[-3:-1]) # แสดงค่าตำแหน่งที่ 1 ตัวสุดท้าย



6. การหาค่าทาง stat ใน numpy โดยใช้คำสั่ง

In [74]:
stat1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(stat1)

# การหาค่า สูงสุด 
print("Max: ", np.max(stat1))
print("Min: ",np.min(stat1))
print("Mean:",np.mean(stat1))
print("Median:", np.median(stat1))
print("Standard Deviation: ", np.std(stat1))
print("Variance: ", np.var(stat1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max:  12
Min:  1
Mean: 6.5
Median: 6.5
Standard Deviation:  3.452052529534663
Variance:  11.916666666666666
